### ISSUE TITLE
Cannot register in 2.77a: '_RestrictData' object has no attribute 'objects'

### ISSUE THREAD

**Issue by RayKoopa** [amoffat/blender-idproperty#1]
I installed the add-on as described (installing from the downloaded repo ZIP), but get the following error as soon as I try to enable it in Blender 2.77a:

```
Traceback (most recent call last):
  File "D:\Archive\Graphics\Blender\2.77\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\Ray\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blender-idproperty-master\__init__.py", line 364, in <module>
    register()
  File "C:\Users\Ray\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blender-idproperty-master\__init__.py", line 344, in register
    load_file()
  File "C:\Users\Ray\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\blender-idproperty-master\__init__.py", line 317, in load_file
    col = getattr(bpy.data, col_name)
AttributeError: '_RestrictData' object has no attribute 'objects'
```

As seen, this happens in the `load_file` method. As far as I heard, `bpy.data` is something like a dummy object at register time, named `_RestrictData`, and will only be resolved later on: http://blender.stackexchange.com/questions/8702/attributeerror-restrictdata-object-has-no-attribute-filepath

Did I do something wrong or is this an issue in newer Blender versions?

**Comment by amoffat** [comment]
hey @RayKoopa.  You were right on this bug... I never noticed it because I don't load the module through the addon section of blender (I do it directly from the Python area).  I just pushed up a couple of commits that should fix the bug.  Re-download the ZIP and give it another try.

**Comment by RayKoopa** [comment]
Thanks! Gonna try it soon =)

**Comment by RayKoopa** [comment]
Works fine now! =)
